name: actions workflow

on: push

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: listing
        run: |
          pwd
          ls 
      - name: simple jS 
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Venky
          