name: actions workflow PR

on: push

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: listing
        run: |
          pwd
          ls -a 
      - name: checkout
        uses: actions/checkout@v3
      - name: list after checkout
        run: |
          pwd
          ls -a 
      - name: simple jS 
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Venky
          